# Generated by Django 5.2.11 on 2026-02-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('DOCTOR', 'Doctor'), ('PHARMACY', 'Pharmacy'), ('ADMIN', 'Admin')], default='DOCTOR', max_length=20),
        ),
    ]
